services:
  mysql:
    image: mysql:8.4
    container_name: connectify-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: connectify
    ports:
      - "3306:3306"
    volumes:
      - connectify_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  connectify_mysql_data:
