spring:
  application:
    name: connectify-backend

  datasource:
    url: jdbc:mysql://localhost:3306/connectify
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath/migration

server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
    org.flywaydb: INFO